### ISSUE TITLE
Don't throw RuntimeError from find/first/last

### ISSUE THREAD

**Issue by royra** [BlackGlory/iterable-operator#4]
JS doesn't tend to use exceptions for flow control.

Returning `undefined` would be more in line with [Array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), [wu.find](https://fitzgen.github.io/wu.js/#find) and [lodash.find](https://lodash.com/docs/4.17.15#find).

**Comment by BlackGlory** [comment]
JS's built-in functions are flawed, which is why I throw exceptions.
Maybe Symbols will be more acceptable?
